POST http://localhost:5000/image/
Content-Type: multipart/form-data; boundary=FormDataRow


--FormDataRow
Content-Disposition: form-data; name="image"; filename="erin2.png"
Content-Type: image/png

< ./erin2.png
--FormDataRow--

###
POST http://localhost:5000/image/
Content-Type: image/png

###
GET  http://localhost:5000/image/5ee1204497a62a75d1e48039


