POST http://localhost:5000/image/
Content-Type: Content-Type: multipart/form-data; boundary=FormDataRow


--FormDataRow
Content-Disposition: form-data; name="image"; filename="test.jpeg"
Content-Type: image/jpeg

< ./test.jpeg
--FormDataRow--