POST http://localhost:5000/image/
Content-Type: multipart/form-data; boundary=FormDataRow


--FormDataRow
Content-Disposition: form-data; name="image"; filename="shoe4.jpg"
Content-Type: image/jpg

< ./shoe4.jpg
--FormDataRow--

###
POST http://localhost:5000/image/
Content-Type: image/png

###
GET  http://localhost:5000/image/5edc94d8d3de906598a18c8f

