POST http://localhost:5000/image/
Content-Type: Content-Type: multipart/form-data; boundary=FormDataRow


--FormDataRow
Content-Disposition: form-data; name="image"; filename="test.jpeg"
Content-Type: image/jpeg

< ./test.jpeg
--FormDataRow--

###
POST http://localhost:5000/image/
Content-Type: image/png

###
GET  http://localhost:5000/image/5ed8a1d6002715418094a859
Content-Type: image/png
