GET http://localhost:5000/order

### 

POST http://localhost:5000/order/
Content-Type: application/json

{
    "productRows": [
    {
      "product":{"_id": "5edc925a1fa50559006c21a8"}
    ,
        "price": 345,
        "items": [{
          "size": 43, 
          "quantity": 2
      }]
    }
  ],
  "user": {
     "_id": "5ec406e317c1af330c67af4f"  
},
  "shipping": {
    "_id": "5ecb88c958785e154a243f79"
  },
  "payment": "Swisch", 
  "date": "2019-12-23 3:4:53",
  "address": {
    "streetAddress": "Norra Gubberogatan 3",
    "postalCode": "41663",
    "city": "Göteborg"
  }
}

### 
PUT http://localhost:5000/order/5ed78fc5fd9fa867b2f51a7d/false
Content-Type: application/json
###

GET http://localhost:5000/order/user/5ec406e317c1af330c67af4f
###



