GET http://localhost:5000/order

### 

POST http://localhost:5000/order/
Content-Type: application/json

{
    "productRows": [
    {
      "product": "5ecbbee7eb3e523b3c7e487b"
    ,
        "price": 229,
        "items": [{
          "size": 34, 
          "quantity": 3
      }]
    }, 
    {
      "product": "5ecd158dc7b859628a329096"
    ,
        "price": 345,
        "items": [{
          "size": 32, 
          "quantity": 2
      }]
    }
  ],
  "user": {
     "_id": "5eca336427dfd7e837facfbd"  
},
  "shipping": {
    "_id": "5ecb88c958785e154a243f79"
  },
  "payment": "Swisch", 
  "date": "2019-12-23 3:4:53",
  "address": {
    "streetAddress": "Norra Gubberogatan 3",
    "postalCode": "41663",
    "city": "Göteborg"
  }
}

### 
PATCH http://localhost:5000/order/5ed78fc5fd9fa867b2f51a7d/false
Content-Type: application/json
###

GET http://localhost:5000/order/user/5ec406e317c1af330c67af4f
###



