GET http://localhost:5000/product/

###

GET http://localhost:5000/product/summer
###
GET http://localhost:5000/product/categories
###

GET http://localhost:5000/product/results

###

POST http://localhost:5000/product/
Content-Type: application/json

  {
    "name" : "CLEO",
    "category": [
      "Party"
    ],
    "price": 1100,
    "description": "Casual and proper OffWhite Cleo",
    "img": "https://vagabondcdn.azureedge.net/thumbnails/3840/1500/crop/productimages/pos2/desktop/4902-101-02.jpg",
    "inventory":
      {
        "size": 36,
         "size": 48,
        "quantity": 10
      }
  }
###

POST http://localhost:5000/product/
Content-Type: application/json

  {
    "name" : "SANDEL JORDANS",
    "category": [
      "street",
      "party"
    ],
    "price": 699,
    "description": "The new airy jordans, the lightest shoe on the market",
    "img": "https://vagabondcdn.azureedge.net/thumbnails/3840/1500/crop/productimages/pos2/desktop/4985-277-54.jpg",
    "inventory":
      [{"size": 43, "quantity": 10},
      {"size": 44, "quantity": 10}]
  }
###

PUT http://localhost:5000/product/5ec7c6a265144bba45e1953e
Content-Type: application/json

{
  "name" : "SETH",
    "category": [
      "Summer",
    ],
    "_id": "5ec7a95d7e0e3eb0d6599ed2",
    "price": 299,
    "description": "The new air jordans, the most valuabel shoe on the market",
    "img": "https://i.ebayimg.com/images/g/UGwAAOSw7TReMxVO/s-l640.jpg",
    "inventory": 
      {
        "size": 42,
        "quantity": 1
      }
  }

###


PUT http://localhost:5000/product/5ecbbee7eb3e523b3c7e487b/42
Content-Type: application/json

{
  "quantity": 5
}
###


PUT http://localhost:5000/product/inventory/5eccf83433c0451eb0e88240
Content-Type: application/json

[{
  "size": 43,
  "quantity" : 2
}]
###

DELETE http://localhost:5000/product/5ec7bf448afe7fb7d8ff9506
    



###


# _Id: ObjectId

# brand: String

# price: Number

# category: String []

# description: String

# inventory: [{
#   size: Number, 
#   quantity: Number
# }]

# img: String


