
GET http://localhost:5000/product/
###

GET http://localhost:5000/product/summer
###

GET http://localhost:5000/product/categories
###

GET http://localhost:5000/product/details/5ee12c4297a62a75d1e48040
###

POST http://localhost:5000/product/5ee12c4297a62a75d1e48040
Content-Type: application/json

      {
        "category": ["formal", "party"],
        "brand": "NEO",
        "price": "1000",
        "description": "Toffee Leather Pumps",
        "inventory": [
          { "size": 36, "quantity": 4 },
          { "size": 38, "quantity": 3 },
          { "size": 42, "quantity": 9 },
          { "size": 45, "quantity": 10 }
        ],
        "image": ["5ee12b2297a62a75d1e4803c"]
      }
###

POST http://localhost:5000/product/
Content-Type: application/json

  {
    "brand" : "D shoe",
    "category": [
      "party", "street"
    ],
    "price": 299,
    "description": "Mid 1990's Robert Parish Game Worn, Signed Shoes",
    "image": "5edbbd3c1fa50559006c21a4",
    "inventory":
      [{"size": 40, "quantity":8},
      {"size": 42, "quantity": 16}]
  }
###

POST http://localhost:5000/product/
Content-Type: application/json

  {
    "brand" : "C shoe",
    "category": [
      "street"
    ],
    "price": 299,
    "description": "Mid 1990's Robert Parish Game Worn, Signed Shoes",
    "image": "5eda4a649be18016fafec1e2",
    "inventory":
      [{"size": 43, "quantity": 10},
      {"size": 44, "quantity": 10}]
  }

PUT http://localhost:5000/product/5eccf83433c0451eb0e88240
Content-Type: application/json

{
  "brand": "test",
    "category": [
      "Summer",
      "Sport"
    ],
    "price": 155,
    "description": "The new air jordans, the most valuabel shoe on the market",
    "image": "5ed9fb6925a96416d8b9ecae",
    "inventory": 
     [ {
        "size": 42,
        "quantity": 12
      }]
  }

###


PUT http://localhost:5000/product/5ecbbee7eb3e523b3c7e487b/42
Content-Type: application/json

{
  "quantity": 5
}
###


PUT http://localhost:5000/product/inventory/5eccf83433c0451eb0e88240
Content-Type: application/json

[{
  "size": 43,
  "quantity" : 2
}]
###

DELETE http://localhost:5000/product/5ec90a21f49ccd608cf9a9ce

    



###


# _Id: ObjectId

# brand: String

# price: Number

# category: String []

# description: String

# inventory: [{
#   size: Number, 
#   quantity: Number
# }]

# img: String


